### ISSUE TITLE
Merging into pmos pmaports

### ISSUE THREAD

**Issue by 1Maxnet1** [NotLugozzi/Xiaomi-daisy-pmOS#2]
Hi I saw you wrote on the pmos-wiki, that you can't merge to the pmaports yet.

May I know what is holding you back? Because the port seems more than good enough for an initial port

**Comment by NotLugozzi** [comment]
Hi, originally what was holding me back was my slow progress and the fact i wasn't getting nowhere so i didn't really think about merging. Just recently i tried following the wiki regarding the git workflow and it didn't work so as a temporary solution i decided to host my port github and then try again with the merge

**Comment by NotLugozzi** [comment]
Quick update, i looked more in the wiki and *actually followed* the steps this time and it worked this time

**Comment by NotLugozzi** [comment]
i take that back - it keeps failing the pipelines for aports-static, saying that apkbuild is an executable file and distifile_check because it says that the checksums in the firmware aren't valid. If you have any idea how to help me with this merge because i think that with failed pipelines developers won't even take a look at it

**Comment by 1Maxnet1** [comment]
> i take that back - it keeps failing the pipelines for aports-static, saying that apkbuild is an executable file and distifile_check because it says that the checksums in the firmware aren't valid. If you have any idea how to help me with this merge because i think that with failed pipelines developers won't even take a look at it

Failing pipelines is not that bad. I'm sorry but I can't help you at the moment but with your merge request opened someone can come across your mr and help you out. If you want, you can additionally ask in the Chat for help: https://wiki.postmarketos.org/wiki/Matrix_and_IRC Thanks you for contributing :+1:
