### ISSUE TITLE
Error pmbootstrap checksum linux-xiaomi-daisy-2

### ISSUE THREAD

**Issue by ghost** [NotLugozzi/Xiaomi-daisy-pmOS#3]
I have a error with execute pmbootstrap checksum linux-xiaomi-daisy-2

Log: 

(24/39) Installing isl24 (0.24-r0)
(25/39) Installing mpfr4 (4.1.0-r0)
(26/39) Installing mpc1 (1.2.1-r0)
(27/39) Installing gcc (12.1.1_git20220630-r1)
(28/39) Installing musl-dev (1.2.3-r1)
(29/39) Installing libc-dev (0.7.2-r3)
(30/39) Installing g++ (12.1.1_git20220630-r1)
(31/39) Installing make (4.3-r0)
(32/39) Installing fortify-headers (1.1-r1)
(33/39) Installing build-base (0.5-r3)
(34/39) Installing hiredis (1.0.2-r1)
(35/39) Installing zstd-libs (1.5.2-r5)
(36/39) Installing ccache (4.6.3-r0)
(37/39) Installing libexpat (2.4.8-r1)
(38/39) Installing pcre2 (10.40-r0)
(39/39) Installing git (2.37.1-r1)
Executing busybox-1.35.0-r24.trigger
Executing ca-certificates-20220614-r2.trigger
OK: 263 MiB in 64 packages
(017240) [22:01:06] (native) % chown root:abuild /var/cache/distfiles
(017240) [22:01:06] (native) % chmod g+w /var/cache/distfiles
(017240) [22:01:06] (native) % cp /tmp/gzip_wrapper.sh /usr/local/bin/gzip
(017240) [22:01:06] (native) % chmod +x /usr/local/bin/gzip
(017240) [22:01:06] (native) % adduser pmos abuild
(017240) [22:01:06] (native) % sed -i -e s/^CLEANUP=.*/CLEANUP=''/ /etc/abuild.conf
(017240) [22:01:06] (native) % sed -i -e s/^ERROR_CLEANUP=.*/ERROR_CLEANUP=''/ /etc/abuild.conf
(017240) [22:01:06] (native) % touch /var/local/pmbootstrap_chroot_build_init_done
(017240) [22:01:06] % sudo cp -rL /home/jose/.local/var/pmbootstrap/cache_git/pmaports/device/community/linux-xiaomi-daisy-2/ /home/jose/.local/var/pmbootstrap/chroot_native/home/pmos/build
(017240) [22:01:06] (native) % chown -R pmos:pmos /home/pmos/build
(017240) [22:01:06] (native) generate checksums for linux-xiaomi-daisy-2
(017240) [22:01:06] (native) % cd /home/pmos/build; busybox su pmos -c HOME=/home/pmos abuild checksum
>>> linux-xiaomi-daisy-2: Fetching linux-xiaomi-daisy-2-80aa9da8ef47805db4c0f987dbbda57a61832874.tar.gz::https://github.com/RebornDaisyProject/daisy_msm8953/archive/80aa9da8ef47805db4c0f987dbbda57a61832874.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  156M    0  156M    0     0  3656k      0 --:--:--  0:00:43 --:--:-- 4238k
>>> ERROR: linux-xiaomi-daisy-2: duplicate found in $source: config-xiaomi-daisy-2.aarch64
(017240) [22:01:50] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(017240) [22:01:50] NOTE: The failed command's output is above the ^^^ line in the log file: /home/jose/.local/var/pmbootstrap/log.txt
(017240) [22:01:50] ERROR: Command failed (exit code 1): (native) % cd /home/pmos/build; busybox su pmos -c HOME=/home/pmos abuild checksum
(017240) [22:01:50] See also: <https://postmarketos.org/troubleshooting>
(017240) [22:01:50] Traceback (most recent call last):
  File "/home/jose/pmbootstrap/pmb/__init__.py", line 49, in main
    getattr(frontend, args.action)(args)
  File "/home/jose/pmbootstrap/pmb/helpers/frontend.py", line 131, in checksum
    pmb.build.checksum.update(args, package)
  File "/home/jose/pmbootstrap/pmb/build/checksum.py", line 16, in update
    pmb.chroot.user(args, ["abuild", "checksum"],
  File "/home/jose/pmbootstrap/pmb/chroot/user.py", line 26, in user
    return pmb.chroot.root(args, cmd, suffix, working_dir, output,
  File "/home/jose/pmbootstrap/pmb/chroot/root.py", line 76, in root
    return pmb.helpers.run_core.core(args, msg, cmd_sudo, None, output,
  File "/home/jose/pmbootstrap/pmb/helpers/run_core.py", line 351, in core
    check_return_code(args, code, log_message)
  File "/home/jose/pmbootstrap/pmb/helpers/run_core.py", line 221, in check_return_code
    raise RuntimeError(f"Command failed (exit code {str(code)}): " +
RuntimeError: Command failed (exit code 1): (native) % cd /home/pmos/build; busybox su pmos -c HOME=/home/pmos abuild checksum

(017572) [22:02:11] % tail -n 60 -F /home/jose/.local/var/pmbootstrap/log.txt
(017572) [22:02:11] *** output passed to pmbootstrap stdout, not to this log ***

**Comment by NotLugozzi** [comment]
Hello; first of all I'd like to apologize on taking so long to reply to the issue. it seems as though you're trying to build this repo's files on top of the files already available in the main pmbootstrap installation; I'd suggest you to run a clean reinstall of pmboostrap (delete all downloaded files, usually located in /var/pmboostrap/) and then follow the instructions available in the device's wiki page; i should've probably also mentioned it in the readme, but the device has been renamed to "daisy" on the main source list. The latest version of the init script for daisy should already include all the necessary files to build and flash both the mainline and downstream kernels.
